language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t docker-frontent-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true docker-frontent-test yarn run test

after_success:
  - docker build -t docker-frontend ./frontend
  - docker build -t docker-backend ./backend
  - docker build -t docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push docker-frontend
  - docker push docker-backend
  - docker push docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-984774476028
  bucket_path: "docker-fullstack-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
