version: '3'
services:
  frontend:
    image: project42da/docker-frontend
    volumes: # 코드 수정후 다시 빌드 없이 수정된 코드가 반영될 수 있도록 
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always # 재시작 정책(no, always, on-failure, unless-stopped)
    image: project42da/docker-nginx
    ports:
      - "80:80"

  backend:
    image: project42da/docker-backend
    container_name: app_backend # 컨테이너명 원하는대로
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
    environment: 
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT